### ISSUE TITLE
Compatibility of the torch-points3d library.

### ISSUE THREAD

**Issue by sfengpeng** [ZhaochongAn/COSeg#16]
Hello, thanks for your great work! However, the torch-points3d library used in the code is only compatible with torch version 1.13.1 at most, which conflicts with the minimum dependency support (torch 2.1.0) required by other libraries in my code. If I want to use your framework and code, how can I resolve this issue?

**Comment by ZhaochongAn** [comment]
Hi, you could just use "pip install --no-dependencies torch_points3d==1.3.0".  It will skip the dependencies check when  installing torch_points3d. Then you could install your own torch version (2.1.0) without any issues.

Since you skip to check the dependencies when installing torch_points3d, you may need to manually install some small packages required by torch_points3d. You will know what these small packages are when running the python code (from the error message). After installing these small packages, the env should be good to run!
